spring:
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ## Data.sql insert
    defer-datasource-initialization: true
#  datasource:
#    jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
#    username: sa
#    password:
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:

    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
